const productos = [
	{
		id: "1",
		nombre: "Moto E13",
		marca: "Motorola",
		precio: 65,
		descripcion: "Camara de 13 MP con inteligencia artificial",
	},
	{
		id: "2",
		nombre: "Moto G32",
		marca: "Motorola",
		precio: 130,
		descripcion: "Obtené horas de potencia, gracias a la batería de 5000 mAh",
	},
	{
		id: "3",
		nombre: "Moto G72",
		marca: "Motorola",
		precio: 202,
		descripcion: "Smartphone Android. Sistema de cámaras con sensor principal de 108 MP",
	},
	{
		id: "4",
		nombre: "Galaxy A34",
		marca: "Samsung",
		precio: 190,
		descripcion: "Es el sucesor del Galaxy A33 5G. Con una pantalla Super AMOLED de 6.6 pulgadas",
	},
	{
		id: "5",
		nombre: "Galaxy M23",
		marca: "Samsung",
		precio: 110,
		descripcion: "Se suma a la serie Galaxy M con una pantalla de 120 Hz",
	},
	{
		id: "6",
		nombre: "Galaxy S20Fe",
		marca: "Samsung",
		precio: 240,
		descripcion: "Mejora tu experiencia de visualización con la pantalla Infinity-O Display",
	},
	{
		id: "7",
		nombre: "Galaxy Tab S6 lite",
		marca: "Samsung",
		precio: 300,
		descripcion: "Aprender desde casa es más fácil, Podrás tomar nota rápidas en Samsung Note con el S Pen",
	},
	{
		id: "8",
		nombre: "30 SE",
		marca: "TCL",
		precio: 95,
		descripcion: "Su fuerte es Precio-calidad",
	},
];